
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_signUpArtista = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_userArt = new javax.swing.JTextField();
        jt_passArt = new javax.swing.JTextField();
        jt_ageArt = new javax.swing.JTextField();
        jt_nombreArtistico = new javax.swing.JTextField();
        jb_crearArtista = new javax.swing.JButton();
        jd_signUpCliente = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt_userCliente = new javax.swing.JTextField();
        jt_passCliente = new javax.swing.JTextField();
        jt_ageCliente = new javax.swing.JTextField();
        jb_crearCliente = new javax.swing.JButton();
        jd_logInArt = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jt_loginArtUser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jt_loginArtPass = new javax.swing.JTextField();
        jb_logInArtista = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jb_logInUser = new javax.swing.JButton();
        jb_signUpUser = new javax.swing.JButton();
        jb_logInArtist = new javax.swing.JButton();
        jb_signUpArtist = new javax.swing.JButton();

        jLabel2.setText("Username");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Edad");

        jLabel5.setText("Nombre artistico");

        jb_crearArtista.setText("SIGN UP");
        jb_crearArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_signUpArtistaLayout = new javax.swing.GroupLayout(jd_signUpArtista.getContentPane());
        jd_signUpArtista.getContentPane().setLayout(jd_signUpArtistaLayout);
        jd_signUpArtistaLayout.setHorizontalGroup(
            jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpArtistaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_ageArt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_passArt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75)
                        .addComponent(jt_userArt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpArtistaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_crearArtista)
                            .addComponent(jt_nombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jd_signUpArtistaLayout.setVerticalGroup(
            jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpArtistaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_userArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_passArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_ageArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jd_signUpArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_nombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jb_crearArtista)
                .addGap(28, 28, 28))
        );

        jLabel6.setText("Username");

        jLabel7.setText("Contraseña");

        jLabel8.setText("Edad");

        jb_crearCliente.setText("SIGN UP");
        jb_crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_signUpClienteLayout = new javax.swing.GroupLayout(jd_signUpCliente.getContentPane());
        jd_signUpCliente.getContentPane().setLayout(jd_signUpClienteLayout);
        jd_signUpClienteLayout.setHorizontalGroup(
            jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_signUpClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_passCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_signUpClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jt_ageCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(75, 75, 75)
                        .addComponent(jt_userCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signUpClienteLayout.createSequentialGroup()
                        .addComponent(jb_crearCliente)
                        .addGap(136, 136, 136)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jd_signUpClienteLayout.setVerticalGroup(
            jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUpClienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_userCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_passCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_signUpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_ageCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jb_crearCliente)
                .addGap(28, 28, 28))
        );

        jLabel9.setText("Username");

        jLabel10.setText("Contraseña");

        jb_logInArtista.setText("LOG IN");
        jb_logInArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logInArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_logInArtLayout = new javax.swing.GroupLayout(jd_logInArt.getContentPane());
        jd_logInArt.getContentPane().setLayout(jd_logInArtLayout);
        jd_logInArtLayout.setHorizontalGroup(
            jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logInArtLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_loginArtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_loginArtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_logInArtLayout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jb_logInArtista)
                    .addContainerGap(169, Short.MAX_VALUE)))
        );
        jd_logInArtLayout.setVerticalGroup(
            jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_logInArtLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_loginArtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_loginArtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(108, 108, 108))
            .addGroup(jd_logInArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_logInArtLayout.createSequentialGroup()
                    .addContainerGap(250, Short.MAX_VALUE)
                    .addComponent(jb_logInArtista)
                    .addGap(27, 27, 27)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Spotify");

        jb_logInUser.setText("LOG IN");

        jb_signUpUser.setText("SIGN UP");
        jb_signUpUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_signUpUserActionPerformed(evt);
            }
        });

        jb_logInArtist.setText("LOG IN as artist");
        jb_logInArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logInArtistActionPerformed(evt);
            }
        });

        jb_signUpArtist.setText("SIGN UP as artist");
        jb_signUpArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_signUpArtistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_signUpArtist)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_signUpUser)
                                .addComponent(jb_logInUser))
                            .addGap(217, 217, 217))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jb_logInArtist)
                            .addGap(197, 197, 197)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jb_logInUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jb_signUpUser)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_logInArtist)
                .addGap(30, 30, 30)
                .addComponent(jb_signUpArtist)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_signUpUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_signUpUserActionPerformed
        jd_signUpCliente.setModal(true);
        jd_signUpCliente.pack();
        jd_signUpCliente.setLocationRelativeTo(this);
        jd_signUpCliente.setVisible(true);
    }//GEN-LAST:event_jb_signUpUserActionPerformed

    private void jb_crearArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearArtistaActionPerformed
        Artista a = new Artista(jt_nombreArtistico.getText(),jt_userArt.getText(),jt_passArt.getText(),Integer.parseInt(jt_ageArt.getText()));
        
        adminUsuarios.getUsers().add(a);
        try {
            adminUsuarios.escribirArchivo();
        } catch (IOException ex) {
        }
        
        jd_signUpArtista.setVisible(false);
        jt_ageArt.setText("");
        jt_nombreArtistico.setText("");
        jt_passArt.setText("");
        jt_userArt.setText("");
    }//GEN-LAST:event_jb_crearArtistaActionPerformed

    private void jb_signUpArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_signUpArtistActionPerformed
        jd_signUpArtista.setModal(true);
        jd_signUpArtista.pack();
        jd_signUpArtista.setLocationRelativeTo(this);
        jd_signUpArtista.setVisible(true);
    }//GEN-LAST:event_jb_signUpArtistActionPerformed

    private void jb_crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearClienteActionPerformed
        Cliente c = new Cliente(jt_userCliente.getText(),jt_passCliente.getText(),Integer.parseInt(jt_ageCliente.getText()));
        
        adminUsuarios.getUsers().add(c);
        try {
            adminUsuarios.escribirArchivo();
        } catch (IOException ex) {
        }
        jt_ageCliente.setText("");
        jt_passCliente.setText("");
        jt_userCliente.setText("");
        jd_signUpCliente.setVisible(false);
    }//GEN-LAST:event_jb_crearClienteActionPerformed

    private void jb_logInArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logInArtistaActionPerformed
        for (int i = 0; i < adminUsuarios.getUsers().size(); i++) {
            if(jt_loginArtUser.getText().equals(adminUsuarios.getUsers().get(i).getUsername()) && jt_loginArtPass.getText().equals(adminUsuarios.getUsers().get(i).getPassword())){
                curUser = adminUsuarios.getUsers().get(i);
                JOptionPane.showMessageDialog(this,"Log in exitoso");
            }else{
                JOptionPane.showMessageDialog(this, "Cagaste");
            }
        }
//        for (int i = 0; i < users.size(); i++) {
//                if (cuenta.equals(users.get(i).getUsername()) && contra.equals(users.get(i).getPassword())) {
//                    username = users.get(i).getNombre();
//                    isAdmin = false;
//                    inAcc = true;
//                    System.out.println("Log in exitoso");
//                } else {
//                }
//            }
    }//GEN-LAST:event_jb_logInArtistaActionPerformed

    private void jb_logInArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logInArtistActionPerformed
        jd_logInArt.setModal(true);
        jd_logInArt.pack();
        jd_logInArt.setLocationRelativeTo(this);
        jd_logInArt.setVisible(true);
    }//GEN-LAST:event_jb_logInArtistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_crearArtista;
    private javax.swing.JButton jb_crearCliente;
    private javax.swing.JButton jb_logInArtist;
    private javax.swing.JButton jb_logInArtista;
    private javax.swing.JButton jb_logInUser;
    private javax.swing.JButton jb_signUpArtist;
    private javax.swing.JButton jb_signUpUser;
    private javax.swing.JDialog jd_logInArt;
    private javax.swing.JDialog jd_signUpArtista;
    private javax.swing.JDialog jd_signUpCliente;
    private javax.swing.JTextField jt_ageArt;
    private javax.swing.JTextField jt_ageCliente;
    private javax.swing.JTextField jt_loginArtPass;
    private javax.swing.JTextField jt_loginArtUser;
    private javax.swing.JTextField jt_nombreArtistico;
    private javax.swing.JTextField jt_passArt;
    private javax.swing.JTextField jt_passCliente;
    private javax.swing.JTextField jt_userArt;
    private javax.swing.JTextField jt_userCliente;
    // End of variables declaration//GEN-END:variables
    public ArrayList <Artista> artistas = new ArrayList();
    public ArrayList <Cliente> clientes = new ArrayList();
    public Usuario curUser;
    adminUsuarios adminUsuarios = new adminUsuarios("./usuarios");
}
